// src/App.jsx
import { useEffect, useState } from "react";
import "./App.css";

function App() {
  const [loading, setLoading] = useState(false);
  const [joke, setJoke] = useState();
  const [version, setVersion] = useState();

  useEffect(() => {
    (async () => {
      setLoading(true);
      const res = await fetch(process.env.REACT_APP_API_URL);

      const { joke, version } = await res.json();

      setJoke(joke);
      setVersion(version);
      setLoading(false);
    })();
  }, [process.env.REACT_APP_API_URL]);

  return (
    <div className="App">
      <div className="navbar bg-base-100">
        <a className="btn btn-ghost normal-case text-xl">
          API Version : {version}
        </a>
        <a className="btn btn-ghost normal-case text-xl">
          Front Version : {process.env.REACT_APP_VERSION}
        </a>
        {loading && (
          <div class="flow-root">
            <div
              class="spinner-border animate-spin inline-block w-8 h-8 border-4 rounded-full float-right"
              role="status"
            >
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        )}
      </div>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold text-red-500">
              {joke?.category}
            </h1>
            <p className="py-6">{joke?.setup}</p>
            <p className="py-6">{joke?.delivery}</p>
            <p className="py-6">{joke?.joke}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// src/App.vue
<script setup>
import { onMounted, ref } from "vue";
const joke = ref();
const version = ref();

onMounted(async () => {
  const res = await fetch("http://localhost:3001");
  const data = await res.json();

  joke.value = data.joke;
  version.value = data.version;
});
</script>

<template>
  <header>
    <div class="navbar bg-base-100">
      <a class="btn btn-ghost normal-case text-xl"
        >API Version : {{ this.version }}</a
      >
      <a class="btn btn-ghost normal-case text-xl">Front Version : 0.0.1</a>
    </div>
  </header>

  <main>
    <div class="hero min-h-screen bg-base-200">
      <div class="hero-content text-center">
        <div class="max-w-md">
          <h1 class="text-5xl font-bold text-red-500">
            {{ this.joke?.category }}
          </h1>
          <p class="py-6">{{ this.joke?.setup }}</p>
          <p class="py-6">{{ this.joke?.delivery }}</p>
          <p class="py-6">{{ this.joke?.joke }}</p>
        </div>
      </div>
    </div>
  </main>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
